import Head from "next/head"

export default function SiteHead() {
    return (
        <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="robots" content="noindex"></meta>
            <meta name="googlebot" content="noindex"></meta>

            <title>Kat & Dan Wedding</title>
            <meta name="description" content="Warehouse and manufacturing units to let from 5,000 - 20,000 sq ft with five acres of development land." />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
    )
}
